language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - master

script:
  - make test

after_script:
  - go build .

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/149378fb1b44bbaf21f0
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    recipients:
      - stan001212@gmail.com
    on_failure: change
    on_success: never
